### ISSUE TITLE
define bot: Fix warnings/errors.

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#4] opened 2017-07-06 19:06 UTC
See https://github.com/zulip/zulip/issues/4960

~~~
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): owlbot.info
ERROR:root:Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
File "bots/define/define.py", line 49, in get_bot_define_response
definitions = api_result.json()
File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
return json.loads(self.text, **kwargs)
File "/usr/lib/python2.7/dist-packages/simplejson/init.py", line 505, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by derAnfaenger** [comment] 2017-08-21 16:41
@abhijeetkaur @neiljp @eeshangarg , has this occurred to anyone of you recently?

**Comment by timabbott** [comment] 2017-08-24 17:36
I haven't seen this.  The issue is I think pretty clear though:
```
                # Use OwlBot API to fetch definition.                                                
                api_result = requests.get(self.DEFINITION_API_URL.format(to_define_lower))           
                # Convert API result from string to JSON format.                                     
                definitions = api_result.json()                                                      
```

We don't check the HTTP status of the `api_result`, so probably what's happening is we're getting a 429 (rate limited) or 500 error.  And those errors aren't JSON-decodable.

**Comment by derAnfaenger** [comment] 2017-08-25 07:53
Hmm, so since there now is a big try-except clause surrounding all problematic code, catching everything, I guess we can close this?
```.py
            try:
                # Use OwlBot API to fetch definition.
                api_result = requests.get(self.DEFINITION_API_URL.format(to_define_lower))
                # Convert API result from string to JSON format.
                definitions = api_result.json()

                # Could not fetch definitions for the given word.
                if not definitions:
                    response += self.REQUEST_ERROR_MESSAGE
                else:  # Definitions available.
                    # Show definitions line by line.
                    for d in definitions:
                        example = d['example'] if d['example'] else '*No example available.*'
                        response += '\n' + '* (**{}**) {}\n&nbsp;&nbsp;{}'.format(d['type'], d['defenition'], html2text.html2text(example))

            except Exception as e:
                response += self.REQUEST_ERROR_MESSAGE
                logging.exception(e)
```

**Comment by derAnfaenger** [comment] 2017-08-25 08:03
I posted a small [commit](https://github.com/zulip/python-zulip-api/pull/95/commits/7098d4111fadcbbc93c4437a9c61e7925ae60aca) for clarifying the error message. Closing this, since the big except block should prevent any errors from happening.

**Closed by derAnfaenger** 2017-08-25 08:03 UTC
